routes/web.php
<?php

Route::get('imagickdev', 'HomeController@imagickdev')->name('imagickdev');
/*
Route::get('qrcode', function () {
	\QrCode::size(500)->format('png')->generate('qrcode.com', public_path('images/qrcode.png'));
	dd(99);
	//return view('employees/qrCode');
});	
*/



Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	
	
	
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Employees
    Route::post('employees/addcertificate/{id}', 'EmployeeController@addcertificate')->name('employees.addcertificate');
	Route::get('employees/listing', 'EmployeeController@listing')->name('employees.listing');    
	Route::delete('employees/destroy', 'EmployeeController@massDestroy')->name('employees.massDestroy');
    Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    Route::resource('employees', 'EmployeeController');
	
	Route::get('internalemployees/showall', 'EmployeeinternalController@index')->name('internalemployees.showall');
	
    Route::get('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::post('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::delete('internalemployees/destroy', 'EmployeeinternalController@massDestroy')->name('internalemployees.massDestroy');
    Route::post('internalemployees/parse-csv-import', 'EmployeeinternalController@parseCsvImport')->name('internalemployees.parseCsvImport');
    Route::post('internalemployees/process-csv-import', 'EmployeeinternalController@processCsvImport')->name('internalemployees.processCsvImport');
    Route::resource('internalemployees', 'EmployeeinternalController');
	
	/*****
	Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    	
	
	/******/
	
	
	Route::get('employees/certificateapprove/{empid}', 'EmployeeController@certificateapprove')->name('employees.certificateapprove');
	Route::get('employees/certificatereview/{empid}', 'EmployeeController@certificatereview')->name('employees.certificatereview');
	Route::get('employees/certificatepdf/{empid}', 'EmployeeController@certificatepdf')->name('employees.certificatepdf');
	

	
	
    // Certificates
    Route::delete('certificates/destroy', 'CertificateController@massDestroy')->name('certificates.massDestroy');
    Route::post('certificates/media', 'CertificateController@storeMedia')->name('certificates.storeMedia');
    Route::post('certificates/ckmedia', 'CertificateController@storeCKEditorImages')->name('certificates.storeCKEditorImages');
    Route::resource('certificates', 'CertificateController');
	
    // Departments
    Route::delete('departments/destroy', 'DepartmentController@massDestroy')->name('departments.massDestroy');
    Route::resource('departments', 'DepartmentController');	
	
    // Members
	Route::get('members/all', 'EmployeeController@allmember')->name('members.all');
    Route::delete('members/destroy', 'MemberController@massDestroy')->name('members.massDestroy');
    Route::post('members/parse-csv-import', 'MemberController@parseCsvImport')->name('members.parseCsvImport');
    Route::post('members/process-csv-import', 'MemberController@processCsvImport')->name('members.processCsvImport');
    Route::resource('members', 'MemberController');	
	
    // Internalmembers
    Route::delete('internalmembers/destroy', 'InternalmemberController@massDestroy')->name('internalmembers.massDestroy');
    Route::post('internalmembers/parse-csv-import', 'InternalmemberController@parseCsvImport')->name('internalmembers.parseCsvImport');
    Route::post('internalmembers/process-csv-import', 'InternalmemberController@processCsvImport')->name('internalmembers.processCsvImport');
    Route::resource('internalmembers', 'InternalmemberController');	
	
	Route::get('/democode','EmployeeController@democode');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

resources/views/partials/menu.blade.php
<aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li class="mt-3">
                            <a href="{{ route("admin.home") }}" class="btn create-btn text-white no-wrap d-flex align-items-center">
                                <i data-feather="plus"></i>
                                <span class="hide-menu ml-2 text-uppercase">{{ trans('global.dashboard') }}</span>
                            </a>
                        </li>
						@can('user_management_access')
							<li class="sidebar-item">
								<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)"
									aria-expanded="false">
									<i data-feather="home" class="mr-2"></i>
									<span class="hide-menu">{{ trans('cruds.userManagement.title') }}</span>
								</a>
								<ul aria-expanded="false" class="collapse  first-level">
									
									@can('permission_access')
										<li class="sidebar-item">
											<a href="{{ route("admin.permissions.index") }}" class="sidebar-link {{ request()->is('admin/permissions') || request()->is('admin/permissions/*') ? 'active' : '' }}">
												<i data-feather="droplet" class="mr-2"></i>
												{{ trans('cruds.permission.title') }}
											</a>
										</li>
									@endcan
									@can('role_access')
										<li class="sidebar-item">
											<a href="{{ route("admin.roles.index") }}" class="sidebar-link {{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active' : '' }}">
												<i data-feather="droplet" class="mr-2"></i>
												{{ trans('cruds.role.title') }}
											</a>
										</li>
									@endcan
									@can('user_access')
										<li class="sidebar-item">
											<a href="{{ route("admin.users.index") }}" class="sidebar-link {{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active' : '' }}">
												<i data-feather="droplet" class="mr-2"></i>
												{{ trans('cruds.user.title') }}
											</a>
										</li>
									@endcan	
								</ul>
							</li>
						@endcan
						
						
						
						
						
						@can('user_management_access')
							<li class="sidebar-item">
								<a class="sidebar-link has-arrow waves-effect waves-dark" href="javascript:void(0)"
									aria-expanded="false">
									<i data-feather="home" class="mr-2"></i>
									<span class="hide-menu">{{ trans('global.certificate') }}</span>
								</a>
								<ul aria-expanded="false" class="collapse  first-level">
										
									
				@can('employee_access')
					<li class="sidebar-item">
						<a href="{{ route("admin.employees.index") }}" class="sidebar-link {{ request()->is('admin/employees') || request()->is('admin/employees/*') ? 'active' : '' }}">
							<i data-feather="droplet" class="mr-2"></i>
							{{ trans('global.external') }}
						</a>
					</li>
					<li class="sidebar-item">
						<a href="{{ route("admin.members.index") }}" class="sidebar-link {{ request()->is('admin/members') || request()->is('admin/members/*') ? 'active' : '' }}">
							<i data-feather="droplet" class="mr-2"></i>
							{{ trans('global.members') }}
						</a>
					</li>					
					<li class="sidebar-item">
						<a href="{{ route("admin.internalemployees.empSearch") }}" class="sidebar-link {{ request()->is('admin/internalemployees') || request()->is('admin/internalemployees/*') ? 'active' : '' }}">
							<i data-feather="droplet" class="mr-2"></i>
							{{ trans('global.internal') }}
						</a>
					</li>
					
					
					<li class="sidebar-item d-none">
						<a href="{{ route("admin.members.all") }}" class="sidebar-link {{ request()->is('admin/members/all') || request()->is('admin/members/all') ? 'active' : '' }}">
							<i data-feather="droplet" class="mr-2"></i>
							{{ trans('global.allmembers') }}
						</a>
					</li>
        @can('internalmember_access')
            <li class="sidebar-item">
                <a href="{{ route("admin.internalmembers.index") }}" class="sidebar-link {{ request()->is('admin/internalmembers') || request()->is('admin/internalmembers/*') ? 'active' : '' }}">
                    <i data-feather="droplet" class="mr-2"></i> 
                    {{ trans('cruds.internalmember.title') }}
                </a>
            </li>
        @endcan						
				@endcan									
									
								</ul>
							</li>
						@endcan
						
						
                    </ul>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        