routes/web.php
<?php

Route::get('imagickdev', 'HomeController@imagickdev')->name('imagickdev');
/*
Route::get('qrcode', function () {
	\QrCode::size(500)->format('png')->generate('qrcode.com', public_path('images/qrcode.png'));
	dd(99);
	//return view('employees/qrCode');
});	
*/



Route::redirect('/', '/login');
Route::get('/home', function () {
    if (session('status')) {
        return redirect()->route('admin.home')->with('status', session('status'));
    }

    return redirect()->route('admin.home');
});

Auth::routes(['register' => false]);
// Admin

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {
	
	
	
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::post('users/media', 'UsersController@storeMedia')->name('users.storeMedia');
    Route::post('users/ckmedia', 'UsersController@storeCKEditorImages')->name('users.storeCKEditorImages');
    Route::resource('users', 'UsersController');

    // Employees
    Route::post('employees/addcertificate/{id}', 'EmployeeController@addcertificate')->name('employees.addcertificate');
	Route::get('employees/listing', 'EmployeeController@listing')->name('employees.listing');    
	Route::delete('employees/destroy', 'EmployeeController@massDestroy')->name('employees.massDestroy');
    Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    Route::resource('employees', 'EmployeeController');
	
	Route::get('internalemployees/showall', 'EmployeeinternalController@index')->name('internalemployees.showall');
	
    Route::get('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::post('internalemployees/search', 'EmployeeinternalController@empSearch')->name('internalemployees.empSearch');
    Route::delete('internalemployees/destroy', 'EmployeeinternalController@massDestroy')->name('internalemployees.massDestroy');
    Route::post('internalemployees/parse-csv-import', 'EmployeeinternalController@parseCsvImport')->name('internalemployees.parseCsvImport');
    Route::post('internalemployees/process-csv-import', 'EmployeeinternalController@processCsvImport')->name('internalemployees.processCsvImport');
    Route::resource('internalemployees', 'EmployeeinternalController');
	
	/*****
	Route::post('employees/parse-csv-import', 'EmployeeController@parseCsvImport')->name('employees.parseCsvImport');
    Route::post('employees/process-csv-import', 'EmployeeController@processCsvImport')->name('employees.processCsvImport');
    	
	
	/******/
	
	
	Route::get('employees/certificateapprove/{empid}', 'EmployeeController@certificateapprove')->name('employees.certificateapprove');
	Route::get('employees/certificatereview/{empid}', 'EmployeeController@certificatereview')->name('employees.certificatereview');
	Route::get('employees/certificatepdf/{empid}', 'EmployeeController@certificatepdf')->name('employees.certificatepdf');
	

	
	
    // Certificates
    Route::delete('certificates/destroy', 'CertificateController@massDestroy')->name('certificates.massDestroy');
    Route::post('certificates/media', 'CertificateController@storeMedia')->name('certificates.storeMedia');
    Route::post('certificates/ckmedia', 'CertificateController@storeCKEditorImages')->name('certificates.storeCKEditorImages');
    Route::resource('certificates', 'CertificateController');
	
    // Departments
    Route::delete('departments/destroy', 'DepartmentController@massDestroy')->name('departments.massDestroy');
    Route::resource('departments', 'DepartmentController');	
	
    // Members
	Route::get('members/all', 'EmployeeController@allmember')->name('members.all');
    Route::delete('members/destroy', 'MemberController@massDestroy')->name('members.massDestroy');
    Route::post('members/parse-csv-import', 'MemberController@parseCsvImport')->name('members.parseCsvImport');
    Route::post('members/process-csv-import', 'MemberController@processCsvImport')->name('members.processCsvImport');
    Route::resource('members', 'MemberController');	
	
    // Internalmembers
    Route::delete('internalmembers/destroy', 'InternalmemberController@massDestroy')->name('internalmembers.massDestroy');
    Route::post('internalmembers/parse-csv-import', 'InternalmemberController@parseCsvImport')->name('internalmembers.parseCsvImport');
    Route::post('internalmembers/process-csv-import', 'InternalmemberController@processCsvImport')->name('internalmembers.processCsvImport');
    Route::resource('internalmembers', 'InternalmemberController');	
	
	Route::get('/democode','EmployeeController@democode');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
// Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

app/Employee.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use \DateTimeInterface;

class Employee extends Model
{
    use SoftDeletes;

    public $table = 'employees';

    protected $dates = [
        'certificate_approve_date',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    const EMPLOYEE_TYPE_SELECT = [
        '1' => 'Internal Employee',
        '2' => 'External Employee',
    ];

    const CERTIFICATE_APPROVAL_STATUS_SELECT = [
        '1' => 'Pending',
        '2' => 'Approved',
        '3' => 'Canceled',
		'4' => 'Reviewed',
    ];

    const EMP_CATEGORY_SELECT = [
        '1' => 'Mr.',
        '2' => 'Mrs.',
        '3' => 'Ms.',
        '4' => 'Dr.',
        '5' => 'Eng.',
		'6' => 'تناتيتسن',
        '7' => 'Others',
    ];

    protected $fillable = [
		'emp_id',
		'emailid',
        'emp_category',
        'first_name',
        'last_name',
		'department',
        'institution_name',
        'issue_date',
        'serial_no',		
        'certificate_approval_status',
        'certificate_approve_by',
        'certificate_qrcode',
        'certificate_approve_date',
        'default_certificate',
        'employee_type',
        'created_by',
		'reviewed_by',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function getCertificateApproveDateAttribute($value)
    {
        return $value ? Carbon::parse($value)->format(config('panel.date_format')) : null;
    }

    public function setCertificateApproveDateAttribute($value)
    {
        $this->attributes['certificate_approve_date'] = $value ? Carbon::createFromFormat(config('panel.date_format'), $value)->format('Y-m-d') : null;
    }
}

app/Http/Controllers/Admin/EmployeeController.php
<?php
namespace App\Http\Controllers\Admin;
use App\Certificate;
use App\Employee;
use App\User;
use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\CsvImportTrait;
use App\Http\Requests\MassDestroyEmployeeRequest;
use App\Http\Requests\StoreEmployeeRequest;
use App\Http\Requests\UpdateEmployeeRequest;
use App\Internalmember;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;
use PDF;
use Auth;
use Libern\QRCodeReader\QRCodeReader;
use Zxing\QrReader;

class EmployeeController extends Controller
{
    use CsvImportTrait;
	
	public function democode(){

		$img = "/images/qrcode/qrcode-1-0-1-27-06-2020-14-50-35.png";
		//echo '<img src="'.$img.'" width="100"    />';QrCode
		
	
$qrcode = new Zxing\QrReader($img);
$text 	= $qrcode->text();
echo $text;
exit;exit;
	/*
		$QRCodeReader = new Libern\QRCodeReader\QRCodeReader();
		$qrcode_text = $QRCodeReader->decode("/images/qrcode/qrcode-1-0-1-27-06-2020-14-50-35.png");
		echo $qrcode_text;		
		dd(555);*/
		
		return view('/admin/employees/democode');
	}
	
	public function allmember(Request $request){
		abort_if(Gate::denies('employee_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$certificate = array();
		$res = Certificate::select('id','certificate_title','department')->get()->toArray();
		
		foreach($res as $val){
			$certificate[$val['id']]['id'] = $val['id'];
			$certificate[$val['id']]['certificate_title'] 	= $val['certificate_title'];
			$certificate[$val['id']]['department'] 			= $val['department'];
		}
		//dd($certificate);
        $employees = Employee::get();
		
		if(Auth::user()->roles[0]->title == 'Admin'){
			$employees = Employee::get();
		}
		elseif(Auth::user()->roles[0]->title == 'Officer'){
			$employees = Employee::where('created_by',Auth::user()->id)->get();
		}
		else{			
			$employees = Employee::where('department',Auth::user()->department)->get();
		}
		
		
        $users = User::all();
		$usersname = array();
		foreach($users as $val){
			$usersname[$val->id] = $val->name;
		}
		$type = 3;
		$mass_actiontxt = '';
		if(Auth::user()->roles[0]->title == 'Manager'){
			$mass_actiontxt = 'Reviewed';
		}
		elseif(Auth::user()->roles[0]->title == 'HOD'){
			$mass_actiontxt = 'Approved';
		}
        return view('admin.employees.external.index', compact('employees','certificate','usersname','type','mass_actiontxt'));
	}
	
    public function index(Request $request)
    {
        abort_if(Gate::denies('employee_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		
		/*
		$type = 'external';
		if($request->type == 'internal'){
			$type = 'internal';
		}
		*/
				$certificate = array();
		$res = Certificate::select('id','certificate_title','department')->get()->toArray();
		
		foreach($res as $val){
			$certificate[$val['id']]['id'] = $val['id'];
			$certificate[$val['id']]['certificate_title'] 	= $val['certificate_title'];
			$certificate[$val['id']]['department'] 			= $val['department'];
		}
		//dd($certificate);
		
		$employees = array();
		$whr = array();
        $whereIn = array();
		$whr['employee_type'] = 2;
		if(Auth::user()->roles[0]->title == 'Admin'){
			$employees = Employee::where($whr)->get();
		}
		elseif(Auth::user()->roles[0]->title == 'Officer'){
			$whr['created_by']		= Auth::user()->id;
			$whr['certificate_approval_status']	= 1;
			$employees = Employee::where($whr)->get();
			//$employees = Employee::where('employee_type',2)->where('created_by',Auth::user()->id)->get();
		}
		elseif(Auth::user()->roles[0]->title == 'Manager'){
			$whr['department']		= Auth::user()->department;
			$employees = Employee::where($whr)->whereIn('certificate_approval_status',[1,4])->get();
			//dd($employees);
			//$employees = Employee::where('employee_type',2)->where('department',Auth::user()->department)->get();
		}
		elseif(Auth::user()->roles[0]->title == 'HOD'){
			$whr['employee_type'] 	= 2;
			$whr['department']		= Auth::user()->department;
			$whr['certificate_approval_status']	= 4;
			$employees = Employee::where($whr)->get();
			//$employees = Employee::where('employee_type',2)->where('department',Auth::user()->department)->get();
		}
		//dd($employees);
		
		
		
        $users = User::all();
		$usersname = array();
		foreach($users as $val){
			$usersname[$val->id] = $val->name;
		}
		$type = 2;
		$mass_actiontxt = '';
		if(Auth::user()->roles[0]->title == 'Manager'){
			$mass_actiontxt = 'Reviewed';
		}
		elseif(Auth::user()->roles[0]->title == 'HOD'){
			$mass_actiontxt = 'Approved';
		}
		//dd($employees);
		
        return view('admin.employees.external.index', compact('employees','certificate','usersname','type','mass_actiontxt'));
		
		
		
		/*
		$certificate = array();
		$res = Certificate::select('id','certificate_title','department')->get()->toArray();
		
		foreach($res as $val){
			$certificate[$val['id']]['id'] = $val['id'];
			$certificate[$val['id']]['certificate_title'] 	= $val['certificate_title'];
			$certificate[$val['id']]['department'] 			= $val['department'];
		}
		//dd($certificate);
        //$employees = Employee::get();

		
		
        $users = User::all();
		$usersname = array();
		foreach($users as $val){
			$usersname[$val->id] = $val->name;
		}
		$type = 2;
		$mass_actiontxt = '';
		if(Auth::user()->roles[0]->title == 'Manager'){
			$mass_actiontxt = 'Reviewed';
		}
		elseif(Auth::user()->roles[0]->title == 'HOD'){
			$mass_actiontxt = 'Approved';
		}
		//dd($employees);
        return view('admin.employees.external.index', compact('employees','certificate','usersname','type','mass_actiontxt'));
		*/
    }

    public function create()
    {
        abort_if(Gate::denies('employee_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$certificate = array();
		//dd(Auth::user()->roles[0]->title);
		if(Auth::user()->roles[0]->title == 'Admin'){
			$res = Certificate::select('id','certificate_title','department')->get()->toArray();
		}
		else{
			$res = Certificate::select('id','certificate_title','department')->where('department',Auth::user()->department)->get()->toArray();
		}
		
		
		foreach($res as $val){
			$certificate[$val['id']]['id'] = $val['id'];
			$certificate[$val['id']]['certificate_title'] = $val['certificate_title'];
			$certificate[$val['id']]['department'] 			= $val['department'];
		}
		$type = 2;
        return view('admin.employees.external.create', compact('certificate','type'));
    }

    public function store(StoreEmployeeRequest $request)
    {
		//dd($request->employee_type);
        $employee = Employee::create($request->all());

		if($request->employee_type == 1){
			return redirect()->route('admin.members.index');
		}
		else{
			return redirect()->route('admin.employees.index');
		}		        
    }

    public function edit(Employee $employee)
    {
        abort_if(Gate::denies('employee_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');
		$certificate = array();
		$res = Certificate::select('id','certificate_title','department')->get()->toArray();
		
		foreach($res as $val){
			$certificate[$val['id']]['id'] = $val['id'];
			$certificate[$val['id']]['certificate_title'] = $val['certificate_title'];
			$certificate[$val['id']]['department'] 			= $val['department'];
		}
        return view('admin.employees.external.edit', compact('employee','certificate'));
    }

    public function update(UpdateEmployeeRequest $request, Employee $employee)
    {
        $employee->update($request->all());
		if($request->employee_type == 1){
			return redirect()->route('admin.members.index');
		}
		else{
			return redirect()->route('admin.employees.index');
		}        
    }

    public function show(Employee $employee)
    {
        abort_if(Gate::denies('employee_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.employees.external.show', compact('employee'));
    }

    public function destroy(Employee $employee)
    {
        abort_if(Gate::denies('employee_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $employee->delete();

        return back();
    }

    public function massDestroy(MassDestroyEmployeeRequest $request)
    {
		//print_r($request->ids);
        
		
		if(Auth::user()->roles[0]->title == 'HOD'){
			$updatedata = array('certificate_approve_by'=>Auth::user()->id,'certificate_approval_status'=>2);
			Employee::whereIn('id', request('ids'))->where('certificate_approval_status',4)->update($updatedata);
		}
		elseif(Auth::user()->roles[0]->title == 'Manager'){			
			$updatedata = array('reviewed_by'=>Auth::user()->id,'certificate_approval_status'=>4);
			Employee::whereIn('id', request('ids'))->where('certificate_approval_status',1)->update($updatedata);
		}
		//print_r($updatedata);
		
		//exit;
		//Employee::whereIn('id', request('ids'))->delete();
        return response(null, Response::HTTP_NO_CONTENT);
    }
	
	public function certificateapprove(Request $request){		
		if(Auth::user()->roles[0]->title == 'HOD'){
			$empid = $request->empid;
			$employee 	= Employee::where('id',$empid)->get();			
			if(isset($employee[0]->certificate_approval_status) && $employee[0]->certificate_approval_status == 4){				
				Employee::where('id',$empid)->update(array('certificate_approval_status'=>2,'certificate_approve_by'=>Auth::user()->id));

				if($employee[0]->employee_type == 2){
					return redirect('admin/employees');
				}
				else{
					return redirect('admin/members');
				}				
			}
		}		
		return redirect('admin/members');
	}
	
	public function certificatereview(Request $request){
		//dd(88);
		if(Auth::user()->roles[0]->title == 'Manager'){
			$empid 		= $request->empid;
			$employee 	= Employee::where('id',$empid)->get();
			if(isset($employee[0]->certificate_approval_status) && $employee[0]->certificate_approval_status == 1){
				$empid = $request->empid;
				Employee::where('id',$empid)->update(array('certificate_approval_status'=>4,'reviewed_by'=>Auth::user()->id));
				if($employee[0]->employee_type == 2){
					return redirect('admin/employees');
				}
				else{

resources/views/admin/employees/external/index.blade.php
<?php //dd($employees)?>
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
		@if($type == 2)
			{{ trans('cruds.employee.title_singular') }} 
		@else
			{{ trans('cruds.employee.internal_certificate') }} 
		@endif	
        {{ trans('global.list') }}
		
		
		

	
@can('employee_create')                        
	@if($type == 2)
		<a class="btn btn-warning float-right" href="{{ route('admin.employees.create') }}">
			{{ trans('global.add') }} <?php /*{{ trans('cruds.employee.title_singular') }}*/?>
		</a>
	@elseif($type == 3)
		<a class="btn btn-success float-right mr-2" href="{{ route('admin.members.create') }}">
			{{ trans('global.add') }} <?php /* {{ trans('cruds.employee.internal_certificate') }}*/?>
		</a> 
		<a class="btn btn-warning float-right mr-2" href="{{ route('admin.employees.create') }}">
			{{ trans('global.add') }} <?php /*{{ trans('cruds.employee.title_singular') }}*/?>
		</a>
	@elseif($type == 4)
		<a class="btn btn-success float-right" href="{{ route('admin.members.create') }}">
			{{ trans('global.add') }} <?php /*{{ trans('global.internal_employee') }}*/?>
		</a>
		<button class="btn btn-warning float-right" data-toggle="modal" data-target="#csvImportModal">
			{{ trans('global.app_csvImport') }}
		</button>	
		@include('csvImport.modal', ['model' => 'Member', 'route' => 'admin.employees.parseCsvImport'])					
	@else
		<a class="btn btn-success float-right" href="{{ route('admin.internalemployees.empSearch') }}">
			{{ trans('global.add') }} <?php /*{{ trans('cruds.employee.internal_certificate') }}*/ ?>
		</a>
		<?php /*<button class="btn btn-warning" data-toggle="modal" data-target="#csvImportModal">
			{{ trans('global.app_csvImport') }}
		</button>
		@include('csvImport.modal', ['model' => 'Employee', 'route' => 'admin.employees.parseCsvImport'])*/ ?>
							
	@endif				            									
@endcan	
	
    </div>	
	
<?php if(session('success')){ ?>
    <div class="col-12">
<div class="alert alert-success fade in alert-dismissible show" style="margin-top:18px;">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
     <span aria-hidden="true" style="font-size:20px">×</span>
  </button>  {{session('success')}}
 </div>
</div>
<?php } ?>
    <div class="card-body">
        <div class="table-responsive">
			<?php //echo Auth::user()->name;?>
            <table class=" table table-bordered table-striped table-hover datatable datatable-Employee">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.id') }}
                        </th>
						@if(in_array($type,array(1,3)))
                        <th>							
                            {{ trans('cruds.employee.fields.emp_id') }}
                        </th>
						@endif
                        <th>							
                            {{ trans('cruds.employee.fields.emp_category') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.first_name') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.last_name') }}
                        </th>
						<th>
                            {{ trans('cruds.employee.fields.emailid') }}
                        </th>
						<th>{{ trans('cruds.employee.fields.department') }}</th>
                        <th>
                            {{ trans('cruds.employee.fields.institution_name') }}
                        </th>
						
						@if($type != 4)						
						<th>
                            {{ trans('cruds.employee.fields.default_certificate') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.certificate_approval_status') }}
                        </th>
						<th>{{ trans('global.created_by') }}</th>
                        <th>{{ trans('global.reviewed_by') }}</th>
                        <th>{{ trans('global.approved_by') }}</th>	
						@endif
						<th>&nbsp;</th>
						
						<?php /*
                        <th>
                            {{ trans('cruds.employee.fields.certificate_approve_by') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.certificate_qrcode') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.certificate_approve_date') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.employee_type') }}
                        </th>
                        <th>
                            {{ trans('cruds.employee.fields.created_by') }}
                        </th>
						*/ ?>
                        
                    </tr>
                </thead>
                <tbody>
                    @foreach($employees as $key => $employee)
						
                        <tr data-entry-id="{{ $employee->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $employee->id ?? '' }}
                            </td>
							
							@if(in_array($type,array(1,3)))
                            <td>
                                {{ $employee->emp_id ?? '' }}
                            </td>
							@endif
                            <td>
								{{ App\Employee::EMP_CATEGORY_SELECT[$employee->emp_category] ?? '' }} 
							</td>
							<td>
								{{ $employee->first_name ?? '' }} 
							</td>
							<td>
								{{ $employee->last_name ?? '' }}
                            </td>
                            <td>
								{{ $employee->emailid ?? '' }}
                            </td>
                            <td>
                                {{ $employee->department ?? '' }}
                            </td>
							<td>
                                {{ $employee->institution_name ?? '' }}
                            </td>
							@if($type != 4)	
							<td>
								@if(isset($certificate[$employee->default_certificate]['certificate_title']))
									<a href="/admin/certificates/{{$employee->default_certificate}}/" target="_blank">
										{{ $certificate[$employee->default_certificate]['certificate_title'] }}
									</a>
								@endif								
                            </td>

                            
                            <td>
								<?php //echo '<pre>';print_r(Auth::user()->roles[0]->title);echo '<pre>';?>
								
								{{ App\Employee::CERTIFICATE_APPROVAL_STATUS_SELECT[$employee->certificate_approval_status] ?? '' }}
								
								
								@if(Auth::user()->roles[0]->title == 'HOD')
									@if(App\Employee::CERTIFICATE_APPROVAL_STATUS_SELECT[$employee->certificate_approval_status] == 'Reviewed')
									<a class="btn btn-xs btn-info" href="{{ route('admin.employees.certificateapprove', $employee->id) }}">
										Approve
									</a>
									@endif	
								@elseif(Auth::user()->roles[0]->title == 'Manager')
									@if(App\Employee::CERTIFICATE_APPROVAL_STATUS_SELECT[$employee->certificate_approval_status] == 'Pending')
									<a class="btn btn-xs btn-info" href="{{ route('admin.employees.certificatereview', $employee->id) }}">
										Review
									</a>	
									@endif
								@endif
								
								
								@if(App\Employee::CERTIFICATE_APPROVAL_STATUS_SELECT[$employee->certificate_approval_status] == 'Approved')
									<a class="btn btn-xs btn-info d-none" href="{{ route('admin.employees.certificatepdf', $employee->id) }}" target="_blank">
										Certificate PDF
									</a>
								@endif																								
                            </td>
                            <td>
								@if(isset($usersname[$employee->created_by]))
									{{ $usersname[$employee->created_by] }}
								@endif
                            </td>                            
                            <td>
								@if(isset($usersname[$employee->reviewed_by]))
									{{ $usersname[$employee->reviewed_by] }}
								@endif
                            </td>                            
                            <td>
								@if(isset($usersname[$employee->certificate_approve_by]))
									{{ $usersname[$employee->certificate_approve_by] }}
								@endif
                            </td>                            							
							@endif
                            <td>
								@if($type != 4)	
									@if(isset($certificate[$employee->default_certificate]['certificate_title']))
										<a class="btn btn-xs @if($employee->certificate_approval_status == 2){{'btn-success'}}@else{{ 'btn-warning' }}@endif" href="{{ route('admin.employees.certificatepdf', $employee->id) }}" target="_blank">
											Certificate
										</a>
									@endif	
								@endif
                                @can('employee_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.employees.show', $employee->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

								@if($employee->certificate_approval_status == 1)
									@can('employee_edit')
										<a class="btn btn-xs btn-info" href="{{ route('admin.employees.edit', $employee->id) }}">
											{{ trans('global.edit') }}
										</a>
									@endcan

									@can('employee_delete')
										<form action="{{ route('admin.employees.destroy', $employee->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
											<input type="hidden" name="_method" value="DELETE">
											<input type="hidden" name="_token" value="{{ csrf_token() }}">
											<input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
										</form>
									@endcan
								@endif
                            </td>
														
                        </tr>
                    @endforeach
                </tbody>
            </table>
        
		
		</div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('employee_delete')
  let deleteButtonTrans = '{{ $mass_actiontxt}}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.employees.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  @if(in_array(Auth::user()->roles[0]->title,array('HOD','Manager')))
  dtButtons.push(deleteButton);
  @endif
  
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-Employee:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection